create database CITYJAIL;

--CREATING TABLES IN THE CITYJAIL DATABASE
CREATE TABLE CRIMINALS(
CRIMINAL_ID NUMERIC (6),
LASTNAME VARCHAR (15),
FIRSTNAME VARCHAR (10),
STREET VARCHAR (30),
CITY VARCHAR (30),
STATE CHAR (2),
ZIP CHAR (5),
PHONE CHAR (10),
V_STATUS CHAR (1),
P_STATUS CHAR (1))

CREATE TABLE PROB_OFFICERS(
PROB_ID NUMERIC (3),
LASTNAME VARCHAR (15),
FIRSTNAME VARCHAR (10),
STREET VARCHAR (30),
CITY VARCHAR (20),
STATE CHAR (2),
ZIP CHAR (5),
PHONE CHAR (10),
EMAIL VARCHAR (30),
STATUS CHAR (1))

CREATE TABLE OFFICERS(
OFFICER_ID NUMERIC (8),
LASTNAME VARCHAR (15),
FIRSTNAME VARCHAR(10),
PRECINCT CHAR (4),
BADGE VARCHAR (14),
PHONE CHAR(10),
STATUS CHAR(1))

CREATE TABLE CRIME_CODES(
CRIME_CODE NUMERIC (3),
CODE_DESCRIPTION VARCHAR (30))

CREATE TABLE CRIMES(
CRIME_ID NUMERIC (9),
CRIMINAL_ID NUMERIC (6),
CLASSIFICATION CHAR (1),
DATE_CHARGED DATE,
STATUS CHAR (2),
HEARING_DATE DATE,
APPEAL_CUT_DATE DATE )

CREATE TABLE ALIASES(
ALIAS_ID NUMERIC (6),
CRIMINAL_ID NUMERIC (6),
ALIAS VARCHAR (10))

CREATE TABLE CRIME_OFFICERS(
CRIME_ID NUMERIC (9),
OFFICER_ID NUMERIC (8))

CREATE TABLE CRIME_CHARGES(
CHARGE_ID NUMERIC (10),
CRIME_ID NUMERIC (9),
CRIME_CODES NUMERIC (3),
CHARGE_STATUS CHAR (2),
FINE_AMOUNT NUMERIC (7),
COURT_FEE NUMERIC (7),
AMOUNT_PAID NUMERIC (7),
PAY_DUE_DATE DATE )

CREATE TABLE SENTENCES(
SENTENCE_ID NUMERIC (6),
CRIMINAL_ID NUMERIC (6),
TYPE CHAR (1),
PROB_ID NUMERIC (5),
START_DATE DATE,
END_DATE DATE,
VIOLATIONS NUMERIC (3) )

CREATE TABLE APPEALS(
APPEAL_ID NUMERIC (5),
CRIME_ID NUMERIC (9),
FILING_DATE DATE,
HEARING_DATE DATE,
STATUS CHAR (1) )

--INSERTING VALUES INTO THE COLUMN "V_STATUS" IN "CRIMINALS" TABLE. Y TO STAND FOR YES AND N TO STAND FOR NO.
INSERT INTO CRIMINALS (V_STATUS)
VALUES ('Y');

INSERT INTO CRIMINALS (V_STATUS)
VALUES ('N');

--INSERTING VALUES INTO THE COLUMN "P_STATUS" IN "CRIMINALS" TABLE. Y TO STAND FOR YES AND n TO STAND FOR NO.
INSERT INTO CRIMINALS (P_STATUS)
VALUES ('Y');

INSERT INTO CRIMINALS (P_STATUS)
VALUES ('N');

--INSERTING VALUES INTO THE "CLASSIFICATION" COLUMN IN "CRIMES" TABLE. F TO STAND FOR FELONY, 
--M TO STAND FOR MISDEMEANOR,O TO STAND FOR OTHER AND U TO STAND FOR UNDEFINED.
INSERT INTO CRIMES (CLASSIFICATION)
VALUES ('F');

INSERT INTO CRIMES (CLASSIFICATION)
VALUES ('M');

INSERT INTO CRIMES (CLASSIFICATION)
VALUES ('O');

INSERT INTO CRIMES (CLASSIFICATION)
VALUES ('U');

--INSERTING VALUES INTO THE "STATUS" COLUMN IN "CRIMES" TABLE. (CL) TO STAND FOR CLOSED, 
--(CA) TO STAND FOR CAN APPEAL, (IA) TO STAND FOR IN APPEAL.
INSERT INTO CRIMES (STATUS)
VALUES ('CL');

INSERT INTO CRIMES (STATUS)
VALUES ('CA');

INSERT INTO CRIMES (STATUS)
VALUES ('IA');

--INSERTING VALUES INTO THE "TYPE" COLUMN IN THE TABLE "SENTENCES".(J) TO STAND FOR JAIL PERIOD,
--(H) TO STAND FOR HOUSE ARREST AND (P) TO STAND FOR PROBATION.
INSERT INTO SENTENCES (TYPE)
VALUES ('J');

INSERT INTO SENTENCES (TYPE)
VALUES ('H');

INSERT INTO SENTENCES (TYPE)
VALUES ('P');


--INSERTING VALUES INTO THE "STATUS" COLUMN IN THE TABLE "PROB_OFFICERS". (A) TO REPRESENT ACTIVE 
--AND (I) TO REPRESENT INACTIVE.
INSERT INTO PROB_OFFICERS (STATUS)
VALUES ('A');

INSERT INTO PROB_OFFICERS (STATUS)
VALUES ('I');


--INSERTING VALUES INTO THE COLUMN "CHARGE_STATUS" IN THE "CRIME_CHARGES" TABLE.(PD) TO STAND FOR PENDING,
--(GL) TO STAND FOR GUILTY AND (NG) TO STAND FOR NOT GUILTY.
INSERT INTO CRIME_CHARGES (CHARGE_STATUS)
VALUES ('PD');

INSERT INTO CRIME_CHARGES (CHARGE_STATUS)
VALUES ('GL');

INSERT INTO CRIME_CHARGES (CHARGE_STATUS)
VALUES ('NG');


--INSERTING VALUES INTO THE "STATUS" COLUMN IN "OFFICERS" TABLE. (A) TO REPRESENT ACTIVE
--AND (I) TO REPRESENT INACTIVE.
INSERT INTO OFFICERS (STATUS)
VALUES ('A');

INSERT INTO OFFICERS (STATUS)
VALUES ('I');


--INSERTING VALUES INTO THE "STATUS" COLUMN IN THE "APPEALS" TABLE. (P) TO REPRESENT PENDING,
--(A) TO REPRESENT APPROVED AND (D) TO REPRESENT DISAPPROVED.
INSERT INTO APPEALS (STATUS)
VALUES ('P');

INSERT INTO APPEALS (STATUS)
VALUES ('A');

INSERT INTO APPEALS (STATUS)
VALUES ('D');


