SELECT DISTINCT CLASSIFICATION FROM CRIMES

----INSERT A DEFAULT VALUE OF U INTO THE "CLASSIFICATION" COLUMN IN "CRIMES" TABLE.
--THE TABLE WILL FIRST BE ALTERED BEFORE THE CHANGE CAN BE MADE
ALTER TABLE CRIMES
ADD CONSTRAINT C_CLASSIFICATION
DEFAULT 'U' FOR CLASSIFICATION;

--INSERTING A NEW COLUMN NAMED "DATE_RECORDED" INTO THE "CRIMES" TABLE.
--THE COLUMN WILL HOLD DATE VALUES AND WILL BE SET TO THE CURRENT DATE BY DEFAULT.
--THE TABLE WILL BE ALTERED TO ACCEPT THIS NEW COLUMN.
ALTER TABLE CRIMES
ADD DATE_RECORDED DATE DEFAULT GETDATE()


--INSERTING A COLUMN TO THE "PROB_OFFICERS" TABLE THAT WILL CONTAIN PHONE NUMBERS AND AREA CODE FOR 
--EACH OFFICER. THE TABLE WILL BE ALTERED TO ACCEPT THIS NEW COLUMN.
ALTER TABLE PROB_OFFICERS
ADD PAGER_NUMBER VARCHAR(30)

--INCREASED THE NUMBER OF CHARACTERS THE ALIAS COLUMN CAN HOLD IN THE ALIASES TABLE.
--THE TABLE WILL BE ALTERED TO ACCEPT THE CHANGE.
ALTER TABLE ALIASES
ALTER COLUMN ALIAS VARCHAR (20);